[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/multitemplate"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  revision = "6db092f778277ef13da427acfa3501890e952436"

[[constraint]]
  name = "github.com/go-gorp/gorp"
  revision = "7357205a98aaeb33d50c45ed613fc6233e52ae8a"

[prune]
  go-tests = true
  unused-packages = true
